/*
 * Copyright 2018 Laszlo Balazs-Csiki and Contributors
 *
 * This file is part of Pixelitor. Pixelitor is free software: you
 * can redistribute it and/or modify it under the terms of the GNU
 * General Public License, version 3 as published by the Free
 * Software Foundation.
 *
 * Pixelitor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Pixelitor. If not, see <http://www.gnu.org/licenses/>.
 */

package pixelitor.assertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;
import pixelitor.selection.Selection;

/**
 * Custom AssertJ assertions for {@link Selection} objects.
 * Based partially on the code generated by CustomAssertionGenerator.
 */
public class SelectionAssert extends AbstractObjectAssert<SelectionAssert, Selection> {
    /**
     * Creates a new <code>{@link SelectionAssert}</code> to make assertions on actual Selection.
     *
     * @param actual the Selection we want to make assertions on.
     */
    public SelectionAssert(Selection actual) {
        super(actual, SelectionAssert.class);
    }

    /**
     * Verifies that the actual Selection is alive.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is not alive.
     */
    public SelectionAssert isAlive() {
        isNotNull();

        // check that property call/field access is true
        if (!actual.isAlive()) {
            failWithMessage("\nExpecting that actual Selection is alive but is not.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is not alive.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is alive.
     */
    public SelectionAssert isNotAlive() {
        isNotNull();

        // check that property call/field access is false
        if (actual.isAlive()) {
            failWithMessage("\nExpecting that actual Selection is not alive but is.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is frozen.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is not frozen.
     */
    public SelectionAssert isFrozen() {
        isNotNull();

        // check that property call/field access is true
        if (!actual.isFrozen()) {
            failWithMessage("\nExpecting that actual Selection is frozen but is not.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is not frozen.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is frozen.
     */
    public SelectionAssert isNotFrozen() {
        isNotNull();

        // check that property call/field access is false
        if (actual.isFrozen()) {
            failWithMessage("\nExpecting that actual Selection is not frozen but is.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is hidden.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is not hidden.
     */
    public SelectionAssert isHidden() {
        isNotNull();

        // check that property call/field access is true
        if (!actual.isHidden()) {
            failWithMessage("\nExpecting that actual Selection is hidden but is not.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is not hidden.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is hidden.
     */
    public SelectionAssert isNotHidden() {
        isNotNull();

        // check that property call/field access is false
        if (actual.isHidden()) {
            failWithMessage("\nExpecting that actual Selection is not hidden but is.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is marching.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is not marching.
     */
    public SelectionAssert isMarching() {
        isNotNull();

        // check that property call/field access is true
        if (!actual.isMarching()) {
            failWithMessage("\nExpecting that actual Selection is marching but is not.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection is not marching.
     *
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection is marching.
     */
    public SelectionAssert isNotMarching() {
        isNotNull();

        // check that property call/field access is false
        if (actual.isMarching()) {
            failWithMessage("\nExpecting that actual Selection is not marching but is.");
        }

        return this;
    }

    /**
     * Verifies that the actual Selection's shape is equal to the given one.
     *
     * @param shape the given shape to compare the actual Selection's shape to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection's shape is not equal to the given one.
     */
    public SelectionAssert hasShape(java.awt.Shape shape) {
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting shape of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        java.awt.Shape actualShape = actual.getShape();
        if (!Objects.areEqual(actualShape, shape)) {
            failWithMessage(assertjErrorMessage, actual, shape, actualShape);
        }

        return this;
    }

    /**
     * Verifies that the actual Selection's shapeBounds is equal to the given one.
     *
     * @param shapeBounds the given shapeBounds to compare the actual Selection's shapeBounds to.
     * @return this assertion object.
     * @throws AssertionError - if the actual Selection's shapeBounds is not equal to the given one.
     */
    public SelectionAssert hasShapeBounds(java.awt.Rectangle shapeBounds) {
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting shapeBounds of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        java.awt.Rectangle actualShapeBounds = actual.getShapeBounds();
        if (!Objects.areEqual(actualShapeBounds, shapeBounds)) {
            failWithMessage(assertjErrorMessage, actual, shapeBounds, actualShapeBounds);
        }

        return this;
    }
}
